demo:
  outputs:
    dev:
      dataset: google_trends
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/src/df_10/dbt/google_service_account.json
      location: US
      method: service-account
      priority: interactive
      project: macro-spider-271508
      threads: 4
      type: bigquery
  target: dev